name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            make \
            git \
            unzip \
            wget \
            gnome-terminal \
            ninja-build \
            openjdk-17-jre-headless \
            libxrandr-dev \
            libxcursor-dev \
            libudev-dev \
            libfreetype-dev \
            libopenal-dev \
            libflac-dev \
            libvorbis-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            g++ \
            gnome-terminal

      - name: Install Gradle
        run: |
          wget -c https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip
          echo "GRADLE_HOME=/opt/gradle/gradle-8.5" >> $GITHUB_ENV
          echo "PATH=/opt/gradle/gradle-8.5/bin:$PATH" >> $GITHUB_ENV

      - name: Print Gradle Version
        run: gradle --version

      - name: Set up g++Android SDK
        uses: android-actions/setup-android@v2

      # - name: Install NDK
      #   run: echo "y" | sdkmanager --install "ndk;26.1.10909125"

      # - name: Print Android Sdk Version
      #   run: sdkmanager --version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build SFML
        run: |
          ./download-ndk-and-build-sfml.sh

      - name: Build Android App
        run: |
          ls -R ~/SFML
          cd ~/SFML/SFML/examples/android
          gradle build
      