name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            make \
            git \
            unzip \
            wget \
            gnome-terminal \
            ninja-build \
            openjdk-17-jre-headless \
            libxrandr-dev \
            libxcursor-dev \
            libudev-dev \
            libfreetype-dev \
            libopenal-dev \
            libflac-dev \
            libvorbis-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev

      - name: Install Gradle
        run: |
          wget -c https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip
          echo "GRADLE_HOME=/opt/gradle/gradle-8.5" >> $GITHUB_ENV
          echo "PATH=/opt/gradle/gradle-8.5/bin:$PATH" >> $GITHUB_ENV

      - name: Print Gradle Version
        run: gradle --version

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: echo "y" | sdkmanager --install "ndk;21.0.6113669"

      - name: Print Android Sdk Version
        run: sdkmanager --version

      - name: Get sfml 2.6
        with:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          git clone https://github.com/SFML/SFML.git
          cd SFML
          git checkout 2.6.1
          mkdir build
          cd build
          mkdir x86_64
          cd x86_64
          echo "NDK_PATH=${{ env.ANDROID_HOME }}ndk/21.0.6113669/" >> $GITHUB_ENV
          cmake -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21 -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_TOOLCHAIN_FILE=${NDK_PATH}build/cmake/android.toolchain.cmake -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=${NDK_PATH} -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../..
          make
          sudo make install