name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deps
        run : |
          sudo apt update && sudo apt install -y \
          cmake \
          make \
          git \
          unzip \
          wget \
          sdkmanager \
          openjdk-17-jre-headless \
          ninja-build

      - name: Accept Android Licenses
        run: |
          echo y | sdkmanager --licenses
      
      - name: Install Android SDK
        run: |
          sdkmanager --install "ndk;26.1.10909125"

      - name: Export Android Home
        run: |
          # use this for act
          echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          # use this for github actions
          # echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build SFML
        run: |
          cd Build-SFML-For-Android-On-Linux
          ./build-sfml.sh $ANDROID_HOME/ndk/26.1.10909125

      - name: Install Gradle
        run: |
          wget -c https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip
          echo "GRADLE_HOME=/opt/gradle/gradle-8.5" >> $GITHUB_ENV
          echo "PATH=/opt/gradle/gradle-8.5/bin:$PATH" >> $GITHUB_ENV

      - name: Build Android App
        run: |
          cd android
          gradle build
      