name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            make \
            git \
            unzip \
            wget \
            gnome-terminal \
            ninja-build \
            openjdk-17-jre-headless \
            libxrandr-dev \
            libxcursor-dev \
            libudev-dev \
            libfreetype-dev \
            libopenal-dev \
            libflac-dev \
            libvorbis-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev

      - name: Install Gradle
        run: |
          wget -c https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip
          echo "GRADLE_HOME=/opt/gradle/gradle-8.5" >> $GITHUB_ENV
          echo "PATH=/opt/gradle/gradle-8.5/bin:$PATH" >> $GITHUB_ENV

      - name: Print Gradle Version
        run: gradle --version

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: echo "y" | sdkmanager --install "ndk;26.1.10909125"

      - name: Print Android Sdk Version
        run: sdkmanager --version

      - name: Fist build to download dependencies
        run: |
          git clone https://github.com/SFML/SFML.git
          cd SFML

      - name: Build sfml for android
        run: |
          cd SFML
          mkdir build
          cd build
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-30 \
            -DSFML_BUILD_ANDROID_EXAMPLES=TRUE \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j 4
          sudo cmake --install . --prefix /usr/local

      - name: Build Android App
        run: |
          cd SFML/examples/android
          git checkout master
          gradle build
      