name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deps
        run : |
          sudo apt update && sudo apt install -y \
          cmake \
          make \
          git \
          unzip \
          wget \
          sdkmanager \
          openjdk-17-jre-headless
          # sdkmanager --licenses
          sdkmanager --install "ndk;26.1.10909125"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build SFML
        run: |
          ./build-sfml.sh /opt/android-sdk/ndk/26.1.10909125

      - name: Install Gradle
        run: |
          wget -c https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip
          echo "GRADLE_HOME=/opt/gradle/gradle-8.5" >> $GITHUB_ENV
          echo "PATH=/opt/gradle/gradle-8.5/bin:$PATH" >> $GITHUB_ENV

      - name: Export Android Home
        run: |
          echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "PATH=/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Build Android App
        run: |
          cd ~/SFML/SFML/examples/android
          gradle build
      